# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('D', '\u0427\u0435\u0440\u043d\u043e\u0432\u0438\u043a'), ('P', '\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d\u043e'), ('E', '\u0423\u0441\u0442\u0430\u0440\u0435\u043b')], default='D', max_length=1),
        ),
    ]
