# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_auto_20160409_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', related_query_name='article', to='Blog.Tag'),
        ),
    ]
