# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_delete_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField()),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
