# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_statistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='article_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.Article'),
        ),
    ]
